
class event_info:
    manual_keywords = ['STORM',
                       'FLOOD',
                       'FLOODING'
                       'CAT',
                       'CATASTROPHE',
                       'BLOCK ENTRY FOR VARIOUS',
                       'BLOCK ENTRY',
                       'HURRICANE',
                       'THUNDERSTROM',
                       'CAT CODE',
                       'PCS',
                       'PCS CODE',
                       'WINDSTORM',
                       'TORNADO',
                       'TYPHOON',
                       'CYCLONE'
                       ]

    cost_center_to_lob = {
        'A':'Various Loss Types',
        'AF':'Non Marine Liability',
        'AG':'Non Marine Liability',
        'AH':'Aviation',
        'AM':'Rig',
        'BA':'Aviation',
        'BB':'Various Loss Types',
        'BC':'Non Marine',
        'BD':'Financial Institutions',
        'BE':'Rig Onshore',
        'BF':'Non Marine Liability',
        'BG':'Financial Institutions',
        'BH':'Hull',
        'BJ':'Liability Offshore',
        'BK':'Satellite',
        'BL':'Liability Onshore',
        'BM':'Casualty',
        'BN':'Non Marine Liability',
        'BP':'Non Marine',
        'BQ':'Liability Offshore',
        'BR':'Rig Onshore',
        'BS':'Specie',
        'BT':'Non Marine Liability',
        'BU':'Casualty',
        'BV':'Cargo',
        'BW':'War',
        'BX':'Financial Institutions',
        'BY':'Financial Institutions',
        'BZ':'Rig Onshore',
        'CA':'Liability Onshore',
        'CD':'Liability Onshore',
        'CE':'Non Marine Liability',
        'CH':'Casualty',
        'CL':'Casualty',
        'CM':'Casualty',
        'CU':'Liability Onshore',
        'CW':'Liability Onshore',
        'CX':'Casualty',
        'CY':'Liability Onshore',
        'DA':'Non Marine Liability',
        'DX':'Contingency',
        'DY':'Liability Onshore',
        'EA':'Aviation',
        'EB':'Non Marine Liability',
        'EC':'Casualty',
        'ED':'Rig',
        'EE':'Non Marine Liability',
        'EF':'Non Marine Liability',
        'EG':'Non Marine Liability',
        'EH':'Casualty',
        'EJ':'Non Marine Liability',
        'EK':'Bloodstock',
        'EL':'Rig',
        'EM':'Rig Onshore',
        'EN':'Rig',
        'EO':'Rig Offshore',
        'EP':'Personal Accident',
        'EQ':'Casualty',
        'FC':'Non Marine Liability',
        'FE':'Non Marine Liability',
        'FX':'Non Marine Liability',
        'GA':'Various Loss Types',
        'GB':'Non Marine Liability',
        'GC':'Non Marine Liability',
        'GD':'Casualty',
        'GE':'Casualty',
        'GH':'Aviation',
        'GJ':'Liability Onshore',
        'GK':'Personal Accident',
        'GL':'Rig',
        'GM':'Casualty',
        'GN':'Non Marine Liability',
        'GO':'Non Marine Liability',
        'GP':'Various Loss Types',
        'GR':'Various Loss Types',
        'GS':'Liability Offshore',
        'GW':'War',
        'GX':'Casualty',
        'GZ':'Non Marine Liability',
        'HA':'Aviation',
        'HG':'Aviation',
        'HP':'Aviation',
        'HX':'Aviation',
        'KA':'Non Marine Liability',
        'KC':'Non Marine Liability',
        'KF':'Non Marine Liability',
        'KG':'Non Marine Liability',
        'KH':'Aviation',
        'KK':'Personal Accident',
        'KL':'Rig',
        'KM':'Motor',
        'KN':'Non Marine Liability',
        'KO':'Non Marine Liability',
        'KP':'Non Marine Liability',
        'KR':'Various Loss Types',
        'KU':'Non Marine Liability',
        'KV':'Non Marine Liability',
        'KW':'War',
        'KX':'Casualty',
        'KY':'Casualty',
        'KZ':'Various Loss Types',
        'LP':'Liability',
        'LX':'Liability Offshore',
        'MD':'Motor',
        'MP':'Motor',
        'MX':'Various Loss Types',
        'NB':'Non Marine Liability',
        'NC':'Non Marine Liability',
        'ND':'Personal Accident',
        'NE':'Non Marine Liability',
        'NF':'Non Marine Liability',
        'NL':'Liability Onshore',
        'NN':'Non Marine',
        'NP':'Non Marine Liability',
        'NR':'Non Marine Liability',
        'NW':'Non Marine Liability',
        'NX':'Bloodstock',
        'PY':'Liability Onshore',
        'RC':'Rig Onshore',
        'RD':'Rig Onshore',
        'RL':'Rig Offshore',
        'RX':'Rig',
        'SL':'Non Marine Liability',
        'SX':'Specie',
        'TE':'Hull',
        'TX':'Hull',
        'TY':'Hull',
        'UA':'Non Marine Liability',
        'UB':'Casualty',
        'UC':'Liability Onshore',
        'UD':'Liability Onshore',
        'UE':'Bloodstock',
        'UF':'Non Marine Liability',
        'UG':'Non Marine Liability',
        'UH':'Personal Accident',
        'UI':'Various Loss Types',
        'UJ':'Various Loss Types',
        'UK':'Non Marine Liability',
        'UL':'Non Marine Liability',
        'UM':'Rig',
        'UN':'Rig',
        'UO':'Casualty',
        'UP':'Non Marine Liability',
        'UQ':'Casualty',
        'UR':'Non Marine Liability',
        'US':'Casualty',
        'UT':'Casualty',
        'UU':'Casualty',
        'UV':'Casualty',
        'UW':'Non Marine Liability',
        'UX':'Rig',
        'UY':'Liability Onshore',
        'VS':'Satellite',
        'VX':'Cargo',
        'WK':'Non Marine Liability',
        'WP':'War',
        'WT':'War',
        'WW':'War',
        'XX':'Motor',
        'YX':'Liability Onshore',
        'Z179':'Motor',
        'ZE':'Casualty',
        'ZH':'Casualty',
        'ZL':'Casualty',
        'ZM':'Casualty',
        'ZU':'NA',
        'ZX':'Liability'
    }
